version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P StrongP@ssw0rd123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline
    depends_on:
      sqlserver:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:StrongP@ssw0rd123@sqlserver:1433/Covid?driver=ODBC+Driver+17+for+SQL+Server"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    volumes:
      - ./data:/app/data
